kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest

- name: publish
  image: plugins/docker
  repo: flask_backend
  settings:
   username:
     from_secret: docker_username
   password:
     from_secret: docker_password
