---
resources:
- name: testrepo
  type: git
  source:
    uri: https://github.com/aleda145/test_repo
    branch: main

- name: flask-backend-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/flask_backend:concourse

jobs:
- name: unit
  plan:
  - get: testrepo
    trigger: true
  - task: unit
    file: testrepo/concourse_test.yml

- name: publish
  public: true
  plan:
  - get: testrepo
    passed: [unit]
    trigger: true
  - put: flask-backend-docker-image
    params:
      build: testrepo